from typing import Any

def sleep(seconds: float) -> None: ...
def sleep_ms(ms: int) -> None: ...
def sleep_us(us: int) -> None: ...

# Include any other native time elements you use so they don't break
def ticks_ms() -> int: ...
def ticks_diff(ticks1: int, ticks2: int) -> int: ...
def ticks_us() -> int: ...